### ISSUE TITLE
error loading mods

### ISSUE THREAD

**Issue by harvey298** [EZForever/ThatOrThis#19]
when starting the mod it will give this error:

`Exception in thread "main" java.lang.NoClassDefFoundError: net/fabricmc/loader/discovery/ModResolutionException
	at io.github.ezforever.thatorthis.Main.run(Main.java:33)
	at io.github.ezforever.thatorthis.PreloadAdapter.<clinit>(PreloadAdapter.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)`

**Comment by EZForever** [comment]
Ooh the inevitable has come...

Please attach the full debug log, or if the log is not available, please report your game and Fabric Loader's version.

**Comment by lenrik1589** [comment]
[build.gradle](https://github.com/EZForever/ThatOrThis/files/7360408/build.gradle.txt)
[gradle.properties](https://github.com/EZForever/ThatOrThis/files/7360413/gradle.properties.txt)
[debug.log](https://github.com/EZForever/ThatOrThis/files/7360403/debug.log)
```java
Exception in thread "main" java.lang.NoClassDefFoundError: net/fabricmc/loader/discovery/ModResolutionException
	at io.github.ezforever.thatorthis.Main.run(Main.java:33)
	at io.github.ezforever.thatorthis.PreloadAdapter.<clinit>(PreloadAdapter.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:411)
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:307)
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:112)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.discovery.ModResolutionException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 11 more
```

**Comment by EZForever** [comment]
OK that's nice to know. v0.2.6 is out containing the fix, you can use Modrinth Maven again.

**Comment by marcohoovy** [comment]
I'm not gonna lie here, but I completely forgot about this so sorry for the late response!

my issue was caused by an version mismatch, similar to the discussion above

**Comment by JustSimplyKyle** [comment]
Using the dev version still doesn't work
![image](https://user-images.githubusercontent.com/68589851/141671235-ebef0af2-2305-4461-a373-43132ba11c18.png)

**Comment by JustSimplyKyle** [comment]
THis is my config
https://www.toptal.com/developers/hastebin/xiwuwufilu.json

**Comment by Felix14-v2** [comment]
@EZForever , hi! I'm sorry to write here, but I don't know a more suitable place for such messages. I know it's been a long time since the first incompatible version of Fabric Loader was released, but I want to say that your amazing mod is still relevant, and it lacks support so much for new Fabric versions. Therefore, I would like to ask if there are any solutions to eliminate incompatibility for now, or can ThatOrThis be considered dead?

**Comment by EZForever** [comment]
@Felix14-v2 , thanks for your support, and I can say ThatOrThis is definitively not dead. I've been missing on this project (or rather, missing on GitHub) was due to some personal things that hit me in the last few months. I will continue developing this mod and try my best to iron out all the issues and incompatibilities, though again, no guarantee is given.

As for the issue mentioned above by KyleUltimate , honestly *I don't know what had happened*. I don't really have any experience of dealing with java modules, the current code is a "throw-things-in-and-hope-it-will-work" approach - well now we know it doesn't work. It launches under development environment, at least.
